### ISSUE TITLE
希望增加脱离token也能调通的接口

### ISSUE THREAD

**Issue by 869123771** [cn2oo8/molicode#11]
魔力code 的代码生成还是挺棒的 ，我想把集成的工程里面来 ， 但是我有自己的登录请求token,  想请求群主给我个 没有登录 和 请求头token 也能调用的molicode 接口 的一个工程 ，，感激不尽。

**Comment by cn2oo8** [comment]
已提交，请下载最新server版本；
并在application.properties文件中添加：
request.token.value=KFDKDOOE9FDKKDKDFKF

token自己设置，请求的时候带上该token值；
