### ISSUE TITLE
希望增加新的前端模板

### ISSUE THREAD

**Issue by lany192** [cn2oo8/molicode#9]
这个工具很不错，点个赞。目前我只看到了vue+iview，希望增加vue+element的代码模板

**Comment by cn2oo8** [comment]
目前有个molicoder在跟进，如果有兴趣是否可以加入一起开发？

**Comment by cn2oo8** [comment]
https://gitee.com/molicode_repo/molicode-template-elementui
已提供elementui的前端模板，不过还在开发阶段，目前测试可用；
